week-12/config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get  "/signup", to: "users#new"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  post "/signup",  to: "users#create"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

week-12/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a><%= link_to "Ruby On Rails Tutorial", "http://www.railstutorial.org/" %></a>
  </small>
  <nav >
    <ul>
      <li><%= link_to t("static_pages.home.about"), "#" %></li>
      <li><%= link_to t("static_pages.home.contact"), "#" %></li>
      <li><%= link_to t("static_pages.home.news"), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

week-12/app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
  <div class = "container">
    <%= link_to t("static_pages.app_name"), root_path, class: "logo" %>
    <nav>
      <ul class = "nav navbar-nav navbar-right">
        <li><%= link_to t("static_pages.home_nav"), root_path %></li>
        <li><%= link_to t("static_pages.help_nav"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("static_pages.users_nav"), users_path %></li>
          <li class="dropdown" >
            <%= link_to "#", data: {toggle: "dropdown"}, class: "dropdown-toggle" do %>
                 <%= t("static_pages.account_nav") %> <b class="caret"> </b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("static_pages.profile_dropdown"), current_user %></li>
              <li><%= link_to t("static_pages.settings_dropdown"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("static_pages.logout_dropdown"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("static_pages.login_nav"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

week-12/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
  <%= render "layouts/header" %>
  <div class = "container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>